### ISSUE TITLE
Not able to run the playbook with scm changes

### ISSUE THREAD

**Issue by nunogrl** [node-ci/nci-ansible-ui-quick-setup#1]
Hello

Thank you for this tool, it looks neat, it seems to work very well :+1: 
 
I'm trying to make it to trigger on changes on the repository, but it's not running the playbooks bit.
Can you help me on this?
I've been digging around the other projects to figure how to use this, but the playbooks bit I couldn't figure so far.

here I figured how to use the scm changes only bit:
https://github.com/node-ci/nci/blob/master/docs/tutorials/standalone-web-ui.md

But when I trigger a build it just finishes after the `steps:` bit and and ignores the `playbooks` section.

Here's my config file:

```
scm:
    type: git
    repository: https://github.com/barbearclassico/nci-ansible-ui-sample-playbook.git
    rev: master

buildEvery:
    time: "*/10 * * * * *"
    withScmChangesOnly: true

#some shell steps before run playbook with inventories
steps:
    - name: Some action before playbooks
      cmd: echo "do something"

playbooks:
    - name: sample_shell_calls
      path: projects/some_project/playbooks/shell/main.yaml
      inventories:
          - name: sample
            path: projects/some_project/inventories/sample/hosts

    - name: check_host_availability
      path: projects/some_project/playbooks/ping/main.yaml
      inventories:
          - name: sample
            path: projects/some_project/inventories/sample/hosts
```

and here's the output:

```
> git show HEAD --pretty=%h⁣⁣%an⁣⁣%ad⁣⁣%s⁣⁣%d
> git fetch origin
> git branch -r
> git show HEAD --pretty=%h⁣⁣%an⁣⁣%ad⁣⁣%s⁣⁣%d
> git checkout -qf master
> git reset --hard origin/master
> git checkout -qf 2d8f9af
> git show HEAD --pretty=%h⁣⁣%an⁣⁣%ad⁣⁣%s⁣⁣%d
> git checkout -qf master
> git merge-base --is-ancestor 2d8f9af master
> git log 2d8f9af..master --pretty=%h⁣⁣%an⁣⁣%ad⁣⁣%s⁣⁣%d  
> git checkout -qf 2d8f9af
> git checkout -qf master
> git submodule update --init --recursive
> git show HEAD --pretty=%h⁣⁣%an⁣⁣%ad⁣⁣%s⁣⁣%d
> git show master --pretty=%h⁣⁣%an⁣⁣%ad⁣⁣%s⁣⁣%d
> /bin/sh -c echo "do something"
do something
```

and here's my `data/config.yaml`:

```
plugins:
    - nci-projects-reloader
    - nci-static-server
    - nci-rest-api-server
    - nci-mail-notification
    - nci-scheduler
    #ui better be last plugin
    - nci-ansible-ui

nodes:
    - type: local
      #allow maximum 3 parallel builds
      maxExecutorsCount: 3

http:
    host: 127.0.0.1
    port: 3000
    url: http://127.0.0.1:3000

    static:
        locations:
            #serve static for ui plugin
            - url: /favicon.ico
              root: node_modules/nci-ansible-ui/static/
            - url: !!js/regexp ^/(js|css|fonts|images)/
              root: node_modules/nci-ansible-ui/static/
storage:
    #use leveldown as db backend
    backend: leveldown
```

and here's the `nci` output when it's scm change triggered:
```
[Mon, 13 Apr 2020 15:21:50 GMT] [scheduler] Run project "smoketest"
[Mon, 13 Apr 2020 15:21:50 GMT] [distributor] Check for scm changes for project "smoketest" on node "local"...
[Mon, 13 Apr 2020 15:21:52 GMT] [distributor] Build #22 (project "smoketest", env: not set) queued
[Mon, 13 Apr 2020 15:21:52 GMT] [distributor] Build #22 (project "smoketest", env: not set) change status: queued -> in-progress
[Mon, 13 Apr 2020 15:21:53 GMT] [distributor] Build #22 (project "smoketest", env: not set) change status: in-progress -> done
[Mon, 13 Apr 2020 15:22:00 GMT] [scheduler] Run project "smoketest"
[Mon, 13 Apr 2020 15:22:00 GMT] [distributor] Check for scm changes for project "smoketest" on node "local"...
[Mon, 13 Apr 2020 15:22:01 GMT] [distributor] Building of "smoketest" skipped coz no scm changes
```

And when it's manually triggered passing the parameters:
```
[Mon, 13 Apr 2020 15:22:30 GMT] [scheduler] Run project "smoketest"
[Mon, 13 Apr 2020 15:22:30 GMT] [distributor] Check for scm changes for project "smoketest" on node "local"...
[Mon, 13 Apr 2020 15:22:31 GMT] [distributor] Building of "smoketest" skipped coz no scm changes
[Mon, 13 Apr 2020 15:22:40 GMT] [scheduler] Run project "smoketest"
[Mon, 13 Apr 2020 15:22:40 GMT] [distributor] Check for scm changes for project "smoketest" on node "local"...
[Mon, 13 Apr 2020 15:22:41 GMT] [distributor] Building of "smoketest" skipped coz no scm changes
[Mon, 13 Apr 2020 15:22:43 GMT] [projects resource] Run the project: "smoketest" with params: {"playbook":{"name":"sample_shell_calls","inventoryNames":["sample"]}}
[Mon, 13 Apr 2020 15:22:43 GMT] [distributor] Build #23 (project "smoketest", env: not set) queued
[Mon, 13 Apr 2020 15:22:43 GMT] [distributor] Build #23 (project "smoketest", env: not set) change status: queued -> in-progress
[Mon, 13 Apr 2020 15:22:50 GMT] [scheduler] Run project "smoketest"
[Mon, 13 Apr 2020 15:22:50 GMT] [distributor] Check for scm changes for project "smoketest" on node "local"...
[Mon, 13 Apr 2020 15:22:51 GMT] [distributor] Building of "smoketest" skipped coz no scm changes
[Mon, 13 Apr 2020 15:22:52 GMT] [distributor] Build #23 (project "smoketest", env: not set) change status: in-progress -> done
[Mon, 13 Apr 2020 15:23:00 GMT] [scheduler] Run project "smoketest"
[Mon, 13 Apr 2020 15:23:00 GMT] [distributor] Check for scm changes for project "smoketest" on node "local"...
[Mon, 13 Apr 2020 15:23:01 GMT] [distributor] Building of "smoketest" skipped coz no scm changes
```

Please advise..  
thanks for your time.

**Comment by okv** [comment]
Hello, currently [scheduler plugin](https://github.com/node-ci/nci-scheduler) (which handles `buildEvery` project settings) doesn't aware of `buildParams` and `buildParams.playbook` is required to build certain playbook. I've planned some updates for nci ansible ui (including [docker image](https://github.com/node-ci/nci-ansible-ui/pull/18), [internal dependencies update](https://github.com/node-ci/nci-ansible-ui/pull/16), etc), I'll try to take a look also on this functionality.

Currently there are 2 ways to trigger playbook:
  * manually, from web interface
  * via http api (using [rest api server plugin](https://github.com/node-ci/nci-rest-api-server)) (e.g. `curl https://127.0.0.1:3000/api/0.1/builds -X POST -d '{"token": "your-secret", "project": "test-project","buildParams": {"playbook": {"name": "some-play", "inventoryNames": ["some-inventory"], "limit": "server1", "extraVars": "hello-world"}}}'
`).

**Comment by nunogrl** [comment]
Thank you for this.
I was really looking forward this. I'm happy that the rest api accepts parameters, so this can be userd.
I made a small ansible playbook role to deploy nci-ansible-ui - https://github.com/nunogrl/ansible-role-nci-ansible-ui .
I suppose is not very mature for the time being, just pushed as a role and added some information on the README.md. (the current daemon setup still requires some work)

My goal was to make a docker as well but I was struggling to build this. Should be easier now, I guess.

**Comment by okv** [comment]
I've added support of `buildParams` to nci scheduler, so it could be used like this:

```yaml
buildEvery:
    time: "*/10 * * * * *"
    buildParams: 
        playbook:
            name: check_host_availability
            inventoryNames: 
                - sample
```

I'll pack this plugin to release image of nci ansible ui.

It's nice to have ansible role :+1: but I recommend to use nodejs 10.x (instead of 8.x) - some new versions of nci plugins will require this.
